### ISSUE TITLE
create a redirect loop

### ISSUE THREAD

**Issue by hechi** [kevinvess/wp-force-login#12]
Hey nice plugin :) and thx for developing.

I got a redirect loop because it uses the $_SERVER stuff. Our wordpress is running in a virtual machine behind a nginx proxy so he took the wrong server address (local addr). I think it would be better and easier to use "get_site_url()" from wordpress it self. 

But i am not really familiar with wordpress and php ^^
Servus

**Comment by kevinvess** [comment]
I'm not sure a fix needs to be made to the plugin for this issue, but rather your web server needs to be fixed to use the PHP predefined variable `$_SERVER`.

Maybe this post is helpful to you:
http://stackoverflow.com/questions/28472692/serverrequest-uri-with-nginx-proxy-server-get-rewritten-page-urls
