### ISSUE TITLE
www redirect issue

### ISSUE THREAD

**Issue by mariabizev** [kevinvess/wp-force-login#16]
Hi there,

I'm using the plugin on my site, and have whitelisted the pages I want using the code below:

```
function my_forcelogin_whitelist( $whitelist ) {
  if( $_GET['auth0'] == 1 ) {
    	$whitelist[] = site_url($_SERVER['REQUEST_URI']);
  }
$whitelist[] = site_url( '/' );
$whitelist[] = site_url( '/whitelistedpage' );
$whitelist[] = site_url( '/whitelistedpage/' );
  return $whitelist;
}
```

This works beautifully. When navigating to a page on the site that is not whitelisted, the user is forced to login and then redirected to the same page.

However, when I navigate to a page that is not whitelisted with the 'www' at the front of my URL, the user is redirected to the homepage. (My WordPress site URL is a non www, and I would like to keep it like that). Additionally, if the user is already logged in, and I navigate to a page that is not whitelisted, they are taken to the login page (without the login form, since they are already logged in) so they are essentially stuck on the empty login page and therefore they cannot access the page they are trying to, despite being logged in. 

_Is there a way to have the 'www' links redirect to my non www site **before** the user is forced to login?_

Any help would be greatly appreciated.

Thanks!

**Comment by kevinvess** [comment]
This is something you should configure with your server; try adding this to your .htaccess file:

```
# Force non-www:
RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ http://%1/$1 [R=301,L]
```

Also, please post support questions at the support forum on WordPress.org:
https://wordpress.org/support/plugin/wp-force-login

GitHub is for reporting bugs in the plugin code.

**Comment by mariabizev** [comment]
Hello,

I actually already added that. It works for whitelisted pages, but not for navigating to a protected page with the 'www' in the front.

**Comment by mariabizev** [comment]
I just read the second part of your message. Sorry about that. I'll be sure to use the Support forum from now on.

**Comment by kevinvess** [comment]
It looks like you started a new thread for this question on the Support forum here:
https://wordpress.org/support/topic/forcelogin-overriding-www-redirect-to-non-www?replies=1

Thanks!
