### ISSUE TITLE
Users added through wp-admin are unable to authenticate their account and set their password.

### ISSUE THREAD

**Issue by Znote** [kevinvess/wp-force-login#19]
Hi

I run a wordpress multisite, where wp-force-login is network enabled across all sites in my development environment. 

Registrations are disabled, however I may add users manually to a site through wp-admin if I set their password and don't require them to authorize their email address. 

But when I add a user and wordpress sends them a registration authentication link, whitelist validation fails in the plugin and they get forced to the login page. 

The registration link is unique to every user (param string), and every site (subdomain), so the whitelist filter dosn't seem to useful since it does full url comparison. Perhaps allow whitelist by url regex?

**Comment by Znote** [comment]
Hmm, perhaps I can validate the url myself by regex/own means, and in case of success just return current url to the whitelist filter?

**Comment by kevinvess** [comment]
The standard WordPress registration URL should already be whitelisted by default. However, if you're using custom URLs for your login and registration URLs, you would need to pass those through the whitelist filter.

To whitelist a dynamic URL (unique URLs with query strings) try one of the following methods outlined here:
https://github.com/kevinvess/wp-force-login/wiki/Whitelist-Dynamic-URLs
