### ISSUE TITLE
Firefox Sometimes Consistently Can't Login

### ISSUE THREAD

**Issue by twmoore3rd** [kevinvess/wp-force-login#2]
*Some* up to date Firefox on Linux, Windows (unknown version), and Mac (unknown version) "can't login". Thankfully I was able to recreate from on a Virtual Box running Mint 14 and up to date Firefox. Upon entering username and password and clicking "Log in", there would be a brief pause with both the username and password being cleared but still on the login screen. No error message would be generated. In looking at the logs, the login would be recorded as successful. If one then had the URL to directly access a particular page, one could access the page. Without logging in, the page is inaccessible.
The behavior is consistent among those stricken with the bug for the particular site. If one could login with FireFox from the particular system, one could always login. Those who could never login were never able to login.
I dropped back to one of the standard WP themes (don't recall the specific theme but it was a 20xx), disabled all plugins, and cleared caches on both the server and in FireFox and still would be shown the same login screen despite having successfully logged in as shown by the logs. 
Observed five times over 200 users. Same users had no problem logging in using Chrome, Safari, or IE from the same system.
Behavior seen on a production system running at WPEngine.com. When I 'cloned" a copy of the production system on to a staging system, the same FireFox browsers that could not login on the production system could log in to the staging site. When I cloned the staging site but to the production site, the same browser that could log in to the staging site could not log in to the new production site.
"Force Login" plugin is currently deactivated and "Require Login" plugin is installed and working without any apparent issues.

**Comment by kevinvess** [comment]
Firefox ver 36.0.4 and ver 37.0.1 on Mac OS 10.10.2 (Yosemite) works as expected for me.

I can't think of why my plugin would work differently based on a users browser; the plugin runs on the server-side. At no point does the plugin code determine what url they're sent to based on the users browser/OS.

More interesting still, you said the plugin works fine in FIrefox while running the site on WPEngine.com's staging environment. There has to be something about your production site's server that is causing the issue, not my plugin code.

Have you tried contacting WPEngine.com support to see if they can help you diagnose why this plugin works on the staging environment and not on the production environment?

**Comment by twmoore3rd** [comment]
I would bet the plugin would work for you. While I wouldn't bet all my paycheck, I would bet most of my paycheck. It did for me on Win 7 and FF 37.0.1 but didn't work for me running a virgin Firefox 37.0.1 install on a virgin Mint 14 install in a Virtual Box. And works for many others. However for the few, Force Login does not allow one to get past the login screen despite having successfully logged in. 

Am all to familiar with how frustrating this soft/intermittent errors are.

I believe a similar behavior was described as an "endless loop" in the plug-in support forum.

As I know nothing about WP innards and what tweaks WPEngine has in place, I will not speculate where the issue lies. :-( "Require Login" is working, I need to have the production system working, so I will be using that plugin. 

"Force Login" is currently deactivated on my production installation. If a new version of Force Login is released, WP will notify me to install it and I will see if I experience the same behavior. The damning bit about my testing is that I can't rule out the behavior is occurring again unless an aware user reports the behavior to me or if I can replicate the behavior on my Virtual Box.

I appreciate and thank you for your time and effort in both developing the plug-in and your response here. Nevertheless, I am at a quandary on how to rate your labor of love, your labor of love that made my life easier for 95% of my users. For the 95% of the users whom the plugin worked, the plug-in deserves a 5-star rating. For those 5%, the plugin rates a 1-star. Weighted average, 4.95-stars, or non-weighted average of 3. Ugh.

As to the resolution of this behavior, your call. Close it out as a "gee that is strange" or keep it open.

Side note: am looking forward to looking at your code versus Require Login code. Realize that I am going to have to spend a lot of time getting to know the WP internal workings.
