### ISSUE TITLE
Plugin doesn't work together with WP-OAuth

### ISSUE THREAD

**Issue by bokysan** [kevinvess/wp-force-login#22]
There's a plugin which enables 3rd-party login with Wordpress: https://github.com/perrybutler/WP-OAuth

Unfortunately, when using it together with Force-Login, the user falls into an infinite loop. **WP-OAuth** works by making a button which creates the following link:

`https://www.example.com/?connect=provider-id&redirect_to=https%3A%2F%2Fwww.example.com%2F`

This link is then parsed by the plugin and a redirect is issued to the correct provider based on provider settings. Unfortunately, this link is caught and parsed by Force-Login before WP-OAuth has time to look at it. And the result is that the user is redirected straight back to the login page before redirect.

User ends up on a "double redirect" login page, e.g.:

https://www.example.com/wp-login.php?redirect_to=https%3A%2F%2Fwww.example.com%2F%3Fconnect%3Dprovider-id%26redirect_to%3Dhttps%253A%252F%252Fwww.example.com%252F

Maybe cooperate with @perrybutler on this?

**Comment by bokysan** [comment]
Seems that just moving the Force-Login to a later stage in the wordpress tree, should be sufficient:

add_action('wp_enqueue_scripts', 'v_forcelogin');

**Comment by kevinvess** [comment]
Instead of moving the `v_forcelogin` action to a later stage in the WordPress tree, have you tried just changing the priority to be later?

```php
add_action('init', 'v_forcelogin', 99);

**Comment by bokysan** [comment]
No, frankly, I haven't. 

I don't believe it would work anyways, as WP-OAuth does most of its magic in `template_redirect`, which happens after `init`.

**Comment by kevinvess** [comment]
Ah, ok – maybe using the same late priority on the `template_redirect` hook would work then?

I'm not opposed to changing the hook when my plugin runs, but I want it to run at an appropriate point in the code. I don't believe having Force Login run at `wp_enqueue_scripts` makes sense.

I choose to have Force Login run at `init` because the WordPress Codex indicated, "Typically used by plugins to initialize. The current user is already authenticated by this time." So, I would think the WP-OAuth plugin would want to ensure the user is logged-in before that point.

Maybe I don't need to change where my plugin hooks it's action, but they should change where their's does.

**Comment by kevinvess** [comment]
Also, instead of altering the source code of my plugin, you could try adding this to your theme's functions.php file to whitelist the WP-OAuth plugin's query string(s):

```php
/**
 * Filter Force Login to allow exceptions for specific URLs.
 *
 * @return array An array of URLs. Must be absolute.
 **/
function my_forcelogin_whitelist( $whitelist ) {
  // whitelist URL if query string contains WP-OAuth query string
  if( isset($_GET['connect']) ) {
    $whitelist[] = site_url($_SERVER['REQUEST_URI']);
  }
  return $whitelist;
}
add_filter('v_forcelogin_whitelist', 'my_forcelogin_whitelist', 10, 1);

**Comment by bokysan** [comment]
RE: Location of firing.

I agree with you completely -- `wp_enqueue_scripts` is not the place to trigger the plugin. I was looking for the last handler that fires before the body is sent and this was it.

I, however, don't believe that `init` is the right place to trigger the plugin, either. Init is used to initialize/setup the plugin -- the actual handling should happen at later stage. `template_redirect` does seem like a more natural fit to fire it. Also the issue is not with _user already authenticated_, but how how the authentication/login takes place. The plugin basically checks the URL for a parameter and if it's there, redirects the user to a third party page. So we are talking about the phase before the user is authenticated.

But in the end, I believe this is something we should be discussing with the author of WP-OAuth (@perrybutler), he'd be able to address your concerns much better.

RE: Workaround.

Much appreciated -- I'll look into it and see if it works.

**Comment by kevinvess** [comment]
I agree, changing Force Login to run at the `template_redirect` hook might be better – I'm going to look into this and run some tests. But that still won't solve your issue with WP-OAuth.

Yes, I realize the issue wasn't with a _user already authenticated_, but I would have thought WP-OAuth would be able to authenticate a user prior to the `init` stage after they clicked the button with the link you mentioned.

For example, the users clicks the button which triggers the page to load again – at which point, WP-OAuth grabs the query and connects the user prior to Force Login running its check/redirect at `init` or `template_redirect`. Makes sense?

You're right, this needs to be discussed with the author of WP-OAuth (@perrybutler) to figure out who needs to change what to make our two plugins work together. I'd be happy to work this out with him.

Thanks for all the great feedback and discussion!

**Comment by bokysan** [comment]
You're welcome and thanks for the help!

Good luck.

**Comment by kevinvess** [comment]
I released a new version of the plugin that now executes on the `template_redirect` hook. Although, this may not completely resolve your issue since the other plugin also executes at the same hook.

However, you could try adding the following code snippet to your theme's `functions.php` file to bypass the _Force Login_ when the `connect` query string parameter is set by the _WP-OAuth_ plugin.

```php
/**
 * Bypass Force Login to allow for exceptions.
 * 
 * @return bool
 */
function my_forcelogin_bypass( $bypass ) {
  if ( isset($_GET['connect']) ) {
  	$bypass = true;
  }
  return $bypass;
}
add_filter('v_forcelogin_bypass', 'my_forcelogin_bypass', 10, 1);
```

**Comment by bokysan** [comment]
I'll check it out, thanks.
