### ISSUE TITLE
Seems to force the screen to the wp-admin

### ISSUE THREAD

**Issue by mhbx** [kevinvess/wp-force-login#24]
I am not sure if this is a new problem... 

I moved my site from one URL to another.  That is the only thing that changed...Till then the force login was functioning as expected. 
Now
When I login to my URL, the new one, it still brings up the login screen, however upon name/pswd entry it did not proceed to the main page as defined, but went to the wp-admin page. 

I have removed the plug in for now.  I don't know if somehow it got confused by the move?  

Thought I'd report it just in case.   If desired I'll recreate the problem and show screen shots or whatever else would be useful.

**Comment by kevinvess** [comment]
1. How exactly did you move your site from one URL to another?

2. When you're on the login screen, does it show a redirect query string? For example:
> /wp-login.php**?redirect_to=http%3A%2F%2Fwww.domain.com%2F**

**Comment by kevinvess** [comment]
I think I might know why the plugin is now redirecting you to the wp-admin page. Force Login uses the `wp_safe_redirect()` function, which ensures a safe (local) redirect:
https://codex.wordpress.org/Function_Reference/wp_safe_redirect

After you changed your site URL, there must be something that is causing the `wp_safe_redirect()` function to think the _redirect_to_ URL being passed is not allowed and is then redirecting to wp-admin on the siteurl instead.

This isn't an issue with Force Login, but instead with how you've migrated your site from one URL to another.

I suggest you ensure the site URL has changed everywhere to your new desired URL. You may want to try these SQL statements to replace all instances of the old URL with the new one (**Backup Your Database First!**):
https://gist.github.com/kevinvess/7686488

In the meantime, you could also use the `wp_safe_redirect_fallback` filter to change the fallback URL from the wp-admin URL to your homepage or something.
https://github.com/WordPress/WordPress/blob/master/wp-includes/pluggable.php#L1262
https://developer.wordpress.org/reference/hooks/wp_safe_redirect_fallback/

**Comment by kevinvess** [comment]
One more suggestion, if you can't get your site to use the new URL properly, you could also try the `allowed_redirect_hosts` filter to tell WordPress to allow both your old and new URLs for redirects.

```php
add_filter( 'allowed_redirect_hosts' , 'my_allowed_redirect_hosts' , 10 );
function my_allowed_redirect_hosts($content){
	$content[] = 'blog.example.com';
	$content[] = 'codex.example.com';
	// wrong: $content[] = 'http://codex.example.com';
	return $content;
}
```

https://codex.wordpress.org/Plugin_API/Filter_Reference/allowed_redirect_hosts
