### ISSUE TITLE
Notice: get_currentuserinfo is deprecated since version 4.5!

### ISSUE THREAD

**Issue by Just-Johnny** [kevinvess/wp-force-login#26]
> Notice: get_currentuserinfo is deprecated since version 4.5! Use wp_get_current_user() instead. in /***/htdocs/wp-includes/functions.php on line 3658

This error started showing today and it's the only plugin I've located in my plugin folder with get_currentuserinfo. If I disable wp-force-login, the error goes away.

**Comment by kevinvess** [comment]
Nice catch, thanks! I'll replace the deprecated function.
