### ISSUE TITLE
Exclude (whitelist) allowed IPs

### ISSUE THREAD

**Issue by WriteCraft** [kevinvess/wp-force-login#29]
Great plugin!  I am using it for an extranet for a client.  They would like to force login from any IPs except their work location.  I was using https://wordpress.org/plugins/force-login-except-special-ip-range/, but it hasn't been updated in 7 years and seems to have quit working.  Any way I can exclude or whitelist IPs in your plugin?  Thanks!

LeeAnne

**Comment by kevinvess** [comment]
Hi– thanks for using Force Login!

You may use the `v_forcelogin_bypass` filter to add an exception for an IP address or any other condition you need.

For example:

```php
/**
 * Bypass Force Login to allow for exceptions.
 *
 * @return bool Whether to disable Force Login. Default false.
 */
function my_forcelogin_bypass( $bypass ) {
  if ( $_SERVER[‘REMOTE_ADDR’] == '127.0.0.1' ) {
    $bypass = true;
  }
  return $bypass;
}
add_filter('v_forcelogin_bypass', 'my_forcelogin_bypass', 10, 1);
```

Keep in mind, using this code has **security implications**. The client can set HTTP header to any arbitrary value it wants. Meaning, someone could trick the server into thinking they're visiting the site with the 127.0.0.1 IP address and bypass the forced login.

**Comment by WriteCraft** [comment]
Worked perfectly!  Thanks!
