### ISSUE TITLE
Redirect filter doesn't work properly after logging out

### ISSUE THREAD

**Issue by jcooper-korg** [kevinvess/wp-force-login#31]
I have added a v_forcelogin_redirect filter to go to my site_url() home page.  This works fine for the first login. 
But after logging out, the site returns to the login page with the URL:
http://mysite/wp-login.php?loggedout=true
Then if i log in again from there, it doesn't redirect to my home page as expected, but shows the user's profile page: http://www.thomas-ranch.org/wp-admin/profile.php
The same thing occurs after the lost-password process.

How can I force it to always go to the home page?
Thanks!
John

**Comment by kevinvess** [comment]
Hi – thanks for using Force Login!

You can force user login to always be sent to the homepage after a successful login. Checkout the following thread on the plugin support forum for two options:
https://wordpress.org/support/topic/redirect-filter-does-not-work-when-logging-in-after-logout/

**Comment by jcooper-korg** [comment]
Thanks Kevin! Much appreciated.
This was the solution:

```
function my_login_redirect($redirect_to, $request, $user) {
  if( !isset($_REQUEST['redirect_to']) )
    return home_url();
  else
    return $redirect_to;
}
add_filter('login_redirect', 'my_login_redirect', 10, 3);
```
