### ISSUE TITLE
How to whitelist certain APIs?

### ISSUE THREAD

**Issue by BettyJJ** [kevinvess/wp-force-login#44]
Hi. First, thank you for writing this useful plugin!

My situation is: I use the WP REST API. I added an API to log user in. I want non-logged-in users to be able to use this API to log in.

I've read the FAQs and am aware of the way to whitelist certain URLs, but whitelisting APIs seems different.
I'm also aware that you can `remove_filter( 'rest_authentication_errors', 'v_forcelogin_rest_access' );`, but I want to  keep other APIs to authorized users only. Only the log-in API needs to be whitelisted.

Please guide me. Thank you!

**Comment by kevinvess** [comment]
Hi, thanks for using Force Login!

The `v_forcelogin_rest_access` filter runs at a later priority of `99` and defers to the result of any other handling plugin. Which means, you could hook into the same filter to pass your authentication status to override Force Login for a specific condition.

For example:
```
/**
 * Report authentication errors to the JSON API
 *
 * @param WP_Error|mixed $result Error from another authentication handler, null if we should handle it, or another value if not
 * @return WP_Error|boolean|null {@see WP_JSON_Server::check_authentication}
 */
function my_rest_authentication( $result ) {
    if ( $result !== null ) {
        return $result;
    }

   // my custom logic here
   // if ( $condition ) {
   //     $result = true;
   // }

   return $result;
}
add_filter( 'rest_authentication_errors', 'my_rest_authentication' );```

**Comment by BettyJJ** [comment]
Thank you for the reply. Can you give me a working example?
Say, my API is `/wp-json/my/v1/login`, how should I write the conditional logic? 
The desired logic is: If `/wp-json/my/v1/login` is requested, then return true.
```
 // if ( $condition ) {     //What exactly should $condition be? 
 //     $result = true;
 // }
```
 Sorry if this seems like a very basic question.

**Comment by kevinvess** [comment]
Sorry, I won't be able to create a working example without actually working on it. The example I gave should be enough to guide you in the right direction. If you need help developing a solution for this, I recommend hiring a developer.

Good luck!

**Comment by BettyJJ** [comment]
I already have an API that works if Force Login is disabled. I just want to add it to Force Login's whitelist since Force Login blocks all api access. From your above comment, I guess it's not easy to do that? Anyway, thank you.
