### ISSUE TITLE
Add Filter for Multisite Unauthorized Error Message

### ISSUE THREAD

**Issue by kevinvess** [kevinvess/wp-force-login#47]
When a logged-in Multisite user tries to access a site they don't belong to, they see the following error message:

> You're not authorized to access this site.

**Feature Request**

Maybe developers should have the ability to change this error message to be specific to their install and be more helpful to their user.

For example, you might want to add detail to the error message that tells users why they're unauthorized or how they may gain access to the site.

**Comment by KeelinJ** [comment]
Hi @kevinvess, is this still on the docket? I'm a happy user of your plugin, and this feature would be a big help. Thanks!

**Comment by kevinvess** [comment]
@KeelinJ Yes– this is still something I plan to implement. Thanks for using Force Login!
