### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by FalsePozitive** [kevinvess/wp-force-login#49]
Hi Bud,

Firstly, thank you very much for this plugin, it full on saved my ass and I thought you might be interested in a use case and a solve. I found another user on wordpress.org who had a similar issue and thought the finding would be useful on the 'Whitelist Dynamic URLs' wiki.

So I have a woocommerce site I'm making for a client which has the following functionality.

1. Site must be totally blocked to unregistered users
2. Users provided with a direct link must be redirected to a specific link once logged in.
3. Users must visit the landing page (custom PHP template) 
4. Contact form must not be affected by redirect. 
5. Contact Form 7 must not be affected by redirect.
6. Facebook Ads must be redirected to Landing Page.

```php
/**
 * Set the URL to redirect to on login.
 *
 * @return string URL to redirect to on login. Must be absolute.
 */
function my_forcelogin_redirect() {
    return home_url( '/welcome-to-unowned/' );
}
add_filter( 'v_forcelogin_redirect', 'my_forcelogin_redirect' );

add_filter( 'woocommerce_login_redirect', 'wc_login_redirect' );

function wc_login_redirect( $redirect_to ) {
	$redirect_to = 'https://unowned.co.uk/welcome-to-unowned/';
	return $redirect_to;
}

/**
 * Filter Force Login to allow exceptions for specific URLs.
 *
 * @param array $whitelist An array of URLs. Must be absolute.
 * @return array
 */
function my_forcelogin_whitelist( $whitelist ) {
	$whitelist[] = home_url( '//' );
	$whitelist[] = home_url( '/landing/#wpcf7-f894-p15-o1/' );
	$whitelist[] = home_url( '/landing/' );
	$whitelist[] = home_url( '/wp-content/themes/dist/welcome.php/' );
	$whitelist[] = home_url( '/wp-content/themes/dist/soon.php/' );
	$whitelist[] = home_url( '/wp-content/plugins/contact-form-7/' );
	return $whitelist;
}
add_filter( 'v_forcelogin_whitelist', 'my_forcelogin_whitelist' );

 /**
 * Bypass Force Login to allow for exceptions.
 *
 * @param bool $bypass Whether to disable Force Login. Default false.
 * @return bool
 */
function my_forcelogin_bypass( $bypass ) {
    // Allow URL if query string 'parameter' exists
    if ( isset( $_GET['fbclid'] ) ) {
        $bypass = true;
    }

    return $bypass;
}
add_filter( 'v_forcelogin_bypass', 'my_forcelogin_bypass' );

function wc_custom_user_redirect( $redirect, $user ) {
	// Get the first of all the roles assigned to the user
	$role = $user->roles[0];
	$dashboard = admin_url();
	$myaccount = get_permalink( wc_get_page_id( 'welcome-to-unowned' ) );
	if( $role == 'administrator' ) {
		//Redirect administrators to the dashboard
		$redirect = $dashboard;
	} elseif ( $role == 'shop-manager' ) {
		//Redirect shop managers to the dashboard
		$redirect = $dashboard;
	} elseif ( $role == 'editor' ) {
		//Redirect editors to the dashboard
		$redirect = $dashboard;
	} elseif ( $role == 'author' ) {
		//Redirect authors to the dashboard
		$redirect = $dashboard;
	} elseif ( $role == 'customer' || $role == 'subscriber' ) {
		//Redirect customers and subscribers to the "My Account" page
		$redirect = $myaccount;
	} else {
		//Redirect any other role to the previous visited page or, if not available, to the home
		$redirect = wp_get_referer() ? wp_get_referer() : home_url();
	}
	return $redirect;
}
add_filter( 'woocommerce_login_redirect', 'wc_custom_user_redirect', 10, 2 );
```

The main fixes I wanted to call attention to which may not be apparent to general users is that your plugin can work perfectly well by whitelisting the Action url parameters for forms, for CF7 just the #... part is necessary.

What was quite a problem is that the Facebook ad campaign was redirecting to login no matter what we tried. I finally got a hold of the URL the marketer was using and it turns out the ads generate an insanely long, parameter filled URL . Using your instructions from the Whitelist URL wiki and using fbclid for the parameter got the ads working again.

I'm aware that this may be blindingly obvious to you but I thought it might be a nice tip to add to the wiki for these edge cases.

Anyway, thanks again for a very useful plugin.

Kind Regards,
James

**Comment by kevinvess** [comment]
Hi James,

Thanks for using Force Login!

And thanks for the thoughtful post, detailing a use-case scenario that others might find helpful.
