### ISSUE TITLE
How to allow REST api only

### ISSUE THREAD

**Issue by skeyuva** [kevinvess/wp-force-login#53]
I have a test site. I want to test some REST apis that i made but during that i want the site to be locked. I tried this plugin and it works for force login and also allows to bypass urls but i could't find any method to bypass my API call. 

Here is a sample url i want to bypass.

` http://my-site.test/wp-json/sk-plugin/make/post `

please help. 
thanks for this plugin.

**Comment by kevinvess** [comment]
Hi– thanks for using Force Login!

Check out these closed tickets for help with this issue: #40 and #44.

**Comment by mkormendy** [comment]
Just add the following code to your functions.php:

remove_filter( 'rest_authentication_errors', 'v_forcelogin_rest_access', 99 );
