### ISSUE TITLE
Conflict with Keyy 2FA Plugin

### ISSUE THREAD

**Issue by TechCoachLisaB** [kevinvess/wp-force-login#54]
If I have your plugin active, regardless of what url I go to (ex: homepage -> redirects to wp-admin, or straight to wp-admin), my Keyy two-factor authentication plugin and app fails.

When this happens Keyy's error is:
 "401 Authorization Error: Please add basic HTTP authentication to site."

I'm not sure how to proceed. Your plugin solves the problem I had with needing the login on the homepage if not logged, but I may have to find another way, as I really enjoy using Keyy. You can find out more about Keyy at getkeyy.com and I'm happy to help in anyway recreate this issue for you.

Thanks! -lmb

**Comment by kevinvess** [comment]
Hi– thanks for using Force Login!

Check out these closed tickets for help with this issue: #40 and #44.

**Comment by TechCoachLisaB** [comment]
Thanks. Issue #40 fixed it.
