### ISSUE TITLE
Forget Password does not work

### ISSUE THREAD

**Issue by Horstvision** [kevinvess/wp-force-login#56]
I work with Force Login for the intern part of a beekeepers site. It works fine, but members are not able to setuo a new password, if they have forgotten their old. 

Can anybody help us ? Sorry, but we are only users not coder.

Thanks, regards
Torsten

**Comment by kevinvess** [comment]
Hi– thanks for using Force Login!

The default WP Lost Password page (`/wp-login.php?action=lostpassword`) should still be accessible; but if your site is using a custom lost password URL, it will need to be added to the `v_forcelogin_bypass` filter to allow it.

Check out the FAQs to see examples of how to whitelist or bypass Force Login for certain pages:
https://wordpress.org/plugins/wp-force-login/#faq

Thanks!
