### ISSUE TITLE
Receiving 302 infinite redirect loop every night (WP v5.5.1, FL v5.4)

### ISSUE THREAD

**Issue by dnestoff** [kevinvess/wp-force-login#57]
We have a wordpress site that's gated for our company employees, in which we use Force Login before users can see that content. We noticed a few months ago (via the plugin Uptime Robot), that our site will be unreachable every day between the hours of 11pm and 6am (MST). After some testing with our .htaccess and then the disabling of plugins, we've identified that this redirect loop is only happening when we have Force Login activated. Furthermore, Force Login is working just fine outside of the 11-6 window.

Our site is Wordpress v5.5.1. And we're using the most recent version of Force Login (v5.4). We do know that the plugin page tells us: "Warning: This plugin has not been tested with your current version of WordPress."

Are there known issues with this version of Wordpress? And are there any configurations we can add to work around this issue?

**Comment by kevinvess** [comment]
Hi– thanks for using Force Login!

I'm not aware of any issues with your version of WordPress.

When you say your "site will be unreachable every day between the hours of 11pm and 6am (MST)" – how is it "unreachable?" What is trying to reach it and failing?

> we've identified that this redirect loop is only happening when we have Force Login activated.

Can you elaborate more on this redirect loop? What URL(s) are in the loop?
