### ISSUE TITLE
Lost your password is not redirecting to the correct page

### ISSUE THREAD

**Issue by peiyic** [kevinvess/wp-force-login#58]
Wordpress version: 5.5.1

When I click "Lost your password?", the URL has changed to "http://totallifechanges.nz/wp-login.php?redirect_to=http%3A%2F%2Ftotallifechanges.nz%2Fmy-account-2%2Flost-password%2F". But it is still redirecting to the login page.

**Comment by kevinvess** [comment]
Hi, thanks for using Force Login!

Your lost password URL (`/my-account-2/lost-password/`) is not a standard WordPress URL. You will need to add an exception to Force Login for any non-standard WordPress URLs you want publicly accessible. Check out the [plugin FAQs](https://wordpress.org/plugins/wp-force-login/#faq) for information on how to do this.

For future reference, please submit support questions to the [plugin's support forum on wordpress.org](https://wordpress.org/support/plugin/wp-force-login/). I use GitHub for development and bug reports.

Thanks!
