### ISSUE TITLE
Version 5.6 causes Wordpress login failure

### ISSUE THREAD

**Issue by dservranckx** [kevinvess/wp-force-login#62]
The latest update changes to the handling of multisites causes a login failure on my multisite installation.

Depending on what type of server I try, I get either
You're not authorized to access this site.  (on my local development laptop) 
OR
a more generic "This page cannot be loaded"

I have restored the previous version from backup and all works fine agian.

What breaks in the new version:
// Only allow Multisite users access to their assigned sites
	if ( is_multisite() && ! is_user_member_of_blog() && ! current_user_can( 'setup_network' ) ) {
		$message = apply_filters( 'v_forcelogin_multisite_message', __( "You're not authorized to access this site.", 'wp-force-login' ), $url );
		
What worked in the previous version:
// Only allow Multisite users access to their assigned sites
		if ( ! is_user_member_of_blog() && ! current_user_can( 'setup_network' ) ) {
			wp_die( __( "You're not authorized to access this site.", 'wp-force-login' ), get_option( 'blogname' ) . ' &rsaquo; ' . __( 'Error', 'wp-force-login' ) );
		}

Thank you
Daniel Servranckx

**Comment by kevinvess** [comment]
Thanks for using Force Login and for your detailed report!

I've just released a new version which should fix this issue. Thanks!

Related issue: #61

**Comment by dservranckx** [comment]
It works, thank you for your quick reply (and fix).

Regards
Daniel.
