### ISSUE TITLE
5.6.2 causes multiple redirect on my (non-multisite) installation

### ISSUE THREAD

**Issue by pjv** [kevinvess/wp-force-login#63]
FYI, I just upgraded a site from version 5.5.0 to 5.6.2 and it causes non-logged-in users to experience a multiple redirect loop error. Downgrading back to 5.5.0 fixed the issue for me. If I have some time later on, I’ll take a look at the last few commits between 5.5.0 and 5.6.2 and see if I can figure out what is causing the issue on my site.

**Comment by kevinvess** [comment]
If you're using a custom login URL – I suspect your issue has to do with that. Version 5.6.2 does work with a default WordPress install.

Feel free to update this issue with your findings.

Thanks!

**Comment by pjv** [comment]
@kevinvess You are correct. I am redirecting from the WP login page to the WooCommerce login page by filtering `login_url`.

With version 5.5 and below of wp-force-login, that worked transparently. For v. 5.6.2 I’ve now had to add an explicit bypass. Given that there may be a redirect string query parameter appended to the URL and also that you probably want to bypass other things like the forgot password URL and/or other my-account related pages, WooCommerce users may want to do what I did:

````
add_filter( 'v_forcelogin_bypass', function ($bypass){
  // Get visited URL without query string
  $url_path = preg_replace('/\?.*/', '', $_SERVER['REQUEST_URI']);
  // allow anything under my-account
  if ( in_array( 'my-account', explode( '/', $url_path ) ) ) {
    $bypass = true;
  }
  return $bypass;
}, 10, 1);
````

**Comment by kevinvess** [comment]
If you're using WooCommerce and need to bypass WC pages, I recommend you use their [conditional tags](https://docs.woocommerce.com/document/conditional-tags/). For example:

```php
/**
 * Bypass Force Login to allow for exceptions.
 *
 * @param bool $bypass Whether to disable Force Login. Default false.
 * @return bool
 */
function my_forcelogin_bypass( $bypass ) {
  // Allow WC customer’s account pages
  if ( is_account_page() ) {
    $bypass = true;
  }
  return $bypass;
}
add_filter( 'v_forcelogin_bypass', 'my_forcelogin_bypass' );
```

**Comment by pjv** [comment]
@kevinvess Thanks very much - that’s better than mine since it doesn’t depend on a hard-coded URL.
