### ISSUE TITLE
Not working in 5.7.2

### ISSUE THREAD

**Issue by tpavesi** [kevinvess/wp-force-login#64]
I can see every page of wordpress without login.

**Comment by kevinvess** [comment]
Thanks for using Force Login!

**Force Login does work in WordPress 5.7.2** and currently has 30,000+ active installations. If you could elaborate more on your particular issue, I might be able to help.

In the future, please submit support questions to the [plugin's support forum on wordpress.org](https://wordpress.org/support/plugin/wp-force-login/).

Good luck!
