### ISSUE TITLE
Possible Bug with Password Reset

### ISSUE THREAD

**Issue by demo38** [kevinvess/wp-force-login#65]
Hello - I like how simple you've made your plugin - but, hitting a snag with the lost password link as it's just reloading the same user login screen instead of the user being able to request a reset password link.

WordPress v5.8
Force Login v5.6.2

Thanks,
Jonathon

**Comment by kevinvess** [comment]
Are you using a custom login URL?

When I test, the password reset link works. For example:

`/wp-login.php?action=rp&key=FlLwhkT6NFHuIvtmmsK2&login=admin&wp_lang=en_US`
