### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by benknight** [kevinvess/wp-force-login#66]
Hello, I'm a developer. I just downloaded and activated this plugin and the site continued to be publicly visible, nothing changed. Please advise how to enable this and confirm it's working.

**Comment by kevinvess** [comment]
Please only post support questions in one place, the [plugin's support forum on wordpress.org](https://wordpress.org/support/plugin/wp-force-login/). I use GitHub for development and bug reports.

I've answered your question here:
https://wordpress.org/support/topic/activated-this-plugin-and-nothing-happened/
