### ISSUE TITLE
Permalinks issues

### ISSUE THREAD

**Issue by mditgr** [kevinvess/wp-force-login#68]
Hello, 

I have installed Force Login on my WordPress website (version 5.8.1) and I am facing an issue with my permalinks as they are not showing as postname anymore. After deactivating the plugin my permalinks restored back to normal. 

Is there anything I can do to fix the issue?

Many thanks in advance.

**Comment by kevinvess** [comment]
Force Login shouldn't affect your permalink settings, it only adds a redirect to WordPress when starts to load a page.

After you activate Force Login, try re-saving your permalink settings? Also clear your server cache?

Good luck!
