### ISSUE TITLE
Force Login should use HTTP_HOST instead of SERVER_NAME.

### ISSUE THREAD

**Issue by Arlen22** [kevinvess/wp-force-login#7]
I have a site which is behind a proxy, and as most proxies pass the original host_name to the server, this plugin should also. I can't think of any reasons why not as far as design considerations, I just know I had to manually change it to use `$_SERVER('HTTP_HOST')` instead of `$_SERVER('SERVER_NAME')`, for it to work right.

**Comment by Arlen22** [comment]
It's actually HTTP_HOST, not HOST_NAME. I've corrected it above as well.

**Comment by kevinvess** [comment]
Thanks for the suggestion, I'll have to try this out.
