### ISSUE TITLE
Problems with WooCommerce's products redirect

### ISSUE THREAD

**Issue by LolliPopPingu** [kevinvess/wp-force-login#70]
Hello,
I installed your plugin but I have a problem on this site:
https://www.reseller.divag.it

As you can see the pages of the site are not visible if you don't login:
https://www.reseller.divag.it/le-collezioni/
https://www.reseller.divag.it/i-gioielli/

instead the product pages are visible, why?
https://www.reseller.divag.it/prodotto/collana-shine-con-croce-pendente-rh-y/
https://www.reseller.divag.it/prodotto/collana-beloved/
https://www.reseller.divag.it/prodotto/collana-square/
https://www.reseller.divag.it/prodotto/collana-beloved-au/

Thank you

**Comment by kevinvess** [comment]
Is the site using the `v_forcelogin_bypass` filter to allow some pages public access?
Otherwise, I don't know why those product pages would be allowed.

**Comment by LolliPopPingu** [comment]
No I don't use any filters, I just installed and activated the plugin

**Comment by kevinvess** [comment]
Force Login runs at the `template_redirect` hook to determine and initiate the redirect to the login screen.

I suspect there is a conflict with another plugin for those pages or post-types which is overriding Force Login's redirect at that hook. You might need to disable other plugins one-by-one to determine which plugin is causing the conflict.
