### ISSUE TITLE
REST API routes not being affected by "v_forcelogin_bypass" filter

### ISSUE THREAD

**Issue by lukic0407** [kevinvess/wp-force-login#72]
When adding a filter to bypass URLs that are related to webpage it works fine, but when adding a URL that is related to REST API in WordPress the bypass filter is not working.

**Comment by kevinvess** [comment]
That's correct, the `v_forcelogin_bypass` filter is for allowing visitors to access a page from the front end.

Force Login restricts the REST API using the [rest_authentication_errors](https://developer.wordpress.org/reference/hooks/rest_authentication_errors/) filter and runs at a late priority of `99` to defer to the result of any other REST API handling. Which means, you could hook into the same filter to pass your authentication status to override Force Login for a specific condition.

For example:
```
/**
 * Bypass Force Login REST API
 *
 * @param WP_Error|mixed $result Error from another authentication handler, null if we should handle it, or another value if not
 * @return WP_Error|boolean|null {@see WP_JSON_Server::check_authentication}
 */
function my_rest_authentication( $result ) {
    if ( $result !== null ) {
        return $result;
    }

   // my custom logic here
   // if ( $condition ) {
   //     $result = true;
   // }

   return $result;
}
add_filter( 'rest_authentication_errors', 'my_rest_authentication' );
```
