### ISSUE TITLE
Whitelisted cyrillic URLs seem to not work

### ISSUE THREAD

**Issue by mikeg-de** [kevinvess/wp-force-login#75]
I am using Polylang and one language is using cyrillic. The second whitelist in the following code seems to not work. The first for english does.

`/**
* Filter Force Login to allow exceptions for specific URLs.
*
* @param array $whitelist An array of URLs. Must be absolute.
* @return array
*/
function my_forcelogin_whitelist( $whitelist ) {
  $whitelist[] = home_url( '/en/legal-notice/' );
  $whitelist[] = home_url( '/ru/правовая-информация/' );

  return $whitelist;
}
add_filter( 'v_forcelogin_whitelist', 'my_forcelogin_whitelist' );
`

**Comment by kevinvess** [comment]
Please don't use the `v_forcelogin_whitelist` filter; it is deprecated and will be removed someday. Use the `v_forcelogin_bypass` filter instead.

[Checkout the FAQ](https://github.com/kevinvess/wp-force-login/wiki/Frequently-Asked-Questions#2-how-can-i-add-exceptions-for-certain-pages-or-posts) for an example of how to use the bypass filter. I recommend using the [is_page()](https://developer.wordpress.org/reference/functions/is_page/) function to identify pages to allow Force Login to bypass.

Thanks!

**Comment by mikeg-de** [comment]
Thanks for pointing that out. I had the other function already present. Maybe too late for me to code ...

However, even after consolidation, it still does not work for cyrillic. English and German are jsut fine.

`/**
 * Bypass Force Login to allow for exceptions.
 *
 * @param bool $bypass Whether to disable Force Login. Default false.
 * @param string $visited_url The visited URL.
 * @return bool
 */
function my_forcelogin_bypass( $bypass, $visited_url ) {

  // Example 1: Allow these pages
  if ( is_page( array( 'register', 'legal-notice', 'impressum', 'правовая-информация' ) ) ) {
    $bypass = true;
  }

  // Example 2: Allow these absolute URLs
  $allowed = array(
//    home_url( '/my-page/' ),
//    home_url( '/2015/03/post-title/' ),
  );
  if ( ! $bypass ) {
    $bypass = in_array( $visited_url, $allowed );
  }

  return $bypass;
}
add_filter( 'v_forcelogin_bypass', 'my_forcelogin_bypass', 10, 2 );`

**Comment by kevinvess** [comment]
Try using the page IDs instead of their language based slug; particularly for the cyrillic pages. Also, delete "Example 2" if you're not going to use it.

```/**
 * Bypass Force Login to allow for exceptions.
 *
 * @param bool $bypass Whether to disable Force Login. Default false.
 * @return bool
 */
function my_forcelogin_bypass( $bypass ) {

  // Allow these pages
  if ( is_page( array( 'register', 'legal-notice', 'impressum', 'правовая-информация' ) ) ) {
    $bypass = true;
  }

  return $bypass;
}
add_filter( 'v_forcelogin_bypass', 'my_forcelogin_bypass' );```

**Comment by mikeg-de** [comment]
Heureka ... I totally forgot about the ID. It is also a much more reliable solution. Though, it means cyrillic isn't quite working but I guess that is neglectible. Would you like to close the ticket?

**Comment by kevinvess** [comment]
I'll leave this issue closed, because I don't believe the cyrillic issue is strictly with Force Login but maybe an issue with WordPress or something unique to your install?

The `is_page( 'правовая-информация' )` function should return true if your page slug matches that string. I'm not sure why that wouldn't work, but it's not something Force Login can fix.
