### ISSUE TITLE
Multiple translated login pages

### ISSUE THREAD

**Issue by mikeg-de** [kevinvess/wp-force-login#76]
Serving a website translated to multiple languages represented via sub-directory like "/en/", "/de/" I was curious if i.e. the auto detect language feature from Polylang could be utilized?

A simplistic approach works by displaying a language switcher and whitelist the other custom login pages.

**Comment by kevinvess** [comment]
Is this a duplicate of issue #77?

**Comment by mikeg-de** [comment]
Not quite. It is only possible to define one login page but not something which maybe takes into consideration the cookie "pll_language" from Polylang or the language sub-directory which, upon first request, Polylang redirects to.

I have found this marvelous solution which I could, with a clear mind in the morning, try to adapt: https://wordpress.org/support/topic/bypass-everywhere-with-query-param/
