### ISSUE TITLE
No redirect to login. Conflict with Polylang?

### ISSUE THREAD

**Issue by mikeg-de** [kevinvess/wp-force-login#77]
I have Polylang in use and translated the website i.e. to "/en/" or "/de/". Though, upon opening the domain w/o a language sub-directory, no redirect is triggered.

Polylang's "Detect browser language" feature is enabled and it worked before. The login page is "/en/register/. No PHP error is logged. Just a blang page with empty head and body. However there is a commetn from W3TotalCache indicating the request is passed through FPM. The Polylang language cookie "pll_language" is set too and carries "en" as a value.

**Comment by kevinvess** [comment]
It sounds like you might be stuck in a redirect loop. You might need to tell Force Login to bypass all your custom language login/register/lost-password pages?

By default, Force Login only allows access to the default WordPress login screen: `/wp-login.php` or whatever the [wp_login_url()](https://developer.wordpress.org/reference/functions/wp_login_url/) function returns as the login screen.

**Comment by mikeg-de** [comment]
My bad ... for whatever that bad reason got cached. I currently cannot reproduce it. Therefore closing the ticket.
