### ISSUE TITLE
Conflict with non-80/433 ports. 

### ISSUE THREAD

**Issue by emmerse** [kevinvess/wp-force-login#8]
If the server is not on 80 or 433, there is some sort of loop happening with the redirect URL, which causes a bad gateway. 

Suggested fix: 

Add a filter on line 31:

`$url .= in_array( $_SERVER['SERVER_PORT'], array('80', '443') ) ? '' : ':' . $_SERVER['SERVER_PORT'];`

to:

`$url .= in_array( $_SERVER['SERVER_PORT'], apply_filters('v_forcelogin_serverports', array('80', '443')) ) ? '' : ':' . $_SERVER['SERVER_PORT'];`

After adding a filter within my functions.php, the plugin behaves as expected.

**Comment by apaeffgen** [comment]
On Wordpress 4.2.xx everything was working fine. Updated to wordpress 4.3, and a to "many redirects error" occurred. In the fix above i also had to manually put in my active sssl port 4443 to get it functional.

**Comment by bornemix** [comment]
Just noticed this on WebMatrix / IISExpress, made a fix for it.

**Comment by kevinvess** [comment]
Hopefully, this is fixed with @bjorn-ali-goransson's pull request #10.
