### ISSUE TITLE
WP Force Login Plugin Conflict w/ The Events Calendar Plugin

### ISSUE THREAD

**Issue by tech4a** [kevinvess/wp-force-login#80]
The Events Calendar Plugin creates:
1.  Events URL slug - events (https://mydomain.com/events/), and 
2. Single event URL slug - event (https://mydomain.com/event/single-post-name/)

When the calendar in number 1 above is loaded, it has 3 views: list, month, and day.  However, it will not change from list view unless the WP Force Login plugin is disabled.  Then all the views function as they should.

![Events Views](https://github.com/kevinvess/wp-force-login/assets/155260011/b2e582d2-1e62-4395-9829-94d0a236d95d)

Also, I tried adding the following code to the Plugin WP Code Lite as a PHP snippet, but there was no change.
Note: I replaced my personal domain in the place of the following part of the code below: https://mydomain.com/events/ 

```php
/**
 * Bypass Force Login to allow for exceptions.
 *
 * @param bool $bypass Whether to disable Force Login. Default false.
 * @param string $visited_url The visited URL.
 * @return bool
 */
function my_forcelogin_bypass( $bypass, $visited_url ) {

  // Allow 'My Page' to be publicly accessible
  if ( is_page('https://mydomain.com/events/') ) {
    $bypass = true;
  }

  return $bypass;
}
add_filter( 'v_forcelogin_bypass', 'my_forcelogin_bypass', 10, 2 );
```

--------------------------------------------------------------

Can anyone speak to this?  Thank you for your insights!!!

**Comment by bobscarpelli** [comment]
I have got the same problem

**Comment by bobscarpelli** [comment]
Thanks for your reply @kevinvess 

I forwarded your message to the Events Calendar Team and they replied the following.

> Upon checking on this further, it seems the issue is due to the REST API restriction from their end.
>  
> See response when the I change the view:
> {
>     "code": "rest_forbidden",
>     "message": "Sorry, you are not allowed to do that.",
>     "data": {
>         "status": 403
>     }
> }
>  
> Request URL: [[domain.com](http://domain.com/)]/wp-json/tribe/views/v2/html
>  
> There could be restrictions applied on their end because it's happening even if the user is already logged in.
>  
> I hope this helps, and let me know if you have further concerns.

Any suggestion? Thanks for your help @kevinvess

**Comment by tech4a** [comment]
Thank you for all of your support!  I'm sorry I have not replied to this
thread in a while.  I will try to study all of this information in depth
and reply as to what results I get!

I REALLY appreciate your support!

Kind regards,
John

**Comment by kevinvess** [comment]
According to @bobscarpelli and the Events Calendar Team, this is because of Force Login's REST API restriction. Check out these closed tickets for help with this: https://github.com/kevinvess/wp-force-login/issues/40 and https://github.com/kevinvess/wp-force-login/issues/44.

**Comment by tech4a** [comment]
Hi Mr. Vess,  

So, the code below did work; however, not being a coder, can you clarify if I am opening any vulnerabilities to my WP site by adding the remove filter code:

remove_filter( 'rest_authentication_errors', 'v_forcelogin_rest_access', 99 );  

to the functions.php file?   Whatever insights you can provide would be much appreciated.

Respectfully,
John

**Comment by kevinvess** [comment]
@tech4a 

> The WordPress REST API provides an interface for applications to interact with your WordPress site by sending and receiving data as [JSON](https://en.wikipedia.org/wiki/JSON) (JavaScript Object Notation) objects.

[https://developer.wordpress.org/rest-api/](https://developer.wordpress.org/rest-api/)

Force Login makes the entire site private and blocks public access to the REST API. By removing that filter, you're allowing the site's REST API to be publicly accessible again. So any pages or posts which are typically considered public in WP could be accessed with an API call to your site.

The ticket #44 offers an example of how to hook into the `rest_authentication_errors` filter to only allow certain APIs public access if you want to code something for only the Events plugin to work.

Good luck!

**Comment by tech4a** [comment]
Kevin,

I'm sorry for the delay.  Thank you for your feedback.  That is helpful.
I'm not a coder, but I will try to analyze ticket #44 and see what I can do.

I appreciate you getting back to me.

Kind regards,
John
