### ISSUE TITLE
I need to bypass an URL but don't know how :(

### ISSUE THREAD

**Issue by brvndonvqz** [kevinvess/wp-force-login#83]
My site is invite only so when I sent the invitation link the URL looks like "example.com/path/key/"

I need to bypass /path/ and /path/w9i0jj0ijxnlxasmpkxmakm/

How Can I do this.

I managed to bypass static URL and string but not this :(

**Comment by kevinvess** [comment]
Hi, thanks for using Force Login!

Check out this wiki page with examples of bypassing dynamic URLs:
[https://github.com/kevinvess/wp-force-login/wiki/Bypass-Dynamic-URLs](https://github.com/kevinvess/wp-force-login/wiki/Bypass-Dynamic-URLs)
