### ISSUE TITLE
Login via Azure (OAuth) isn't redirecting me to the URL I tried to access

### ISSUE THREAD

**Issue by aurooj-khan** [kevinvess/wp-force-login#84]
When I login via Azure (we integrated this into Wordpress login), I'm being sent to the Homepage of my website, even though the URL I was trying to access was for a different page on the site.

**Comment by kevinvess** [comment]
Hello,

Force Login is built to work with the default WordPress login functionality.

If you're using a SSO service (like Azure) to handle logging in, then what happens to the user after logging in is not determined by Force Login.

For future reference, please submit support questions to the [plugin's support forum on wordpress.org](https://wordpress.org/support/plugin/wp-force-login/). I use GitHub for development and bug reports.
